src/app/ng2-mask/mask.directive.ts

Renderer is deprecated.  Update to Renderer2.
setting disabled to false doesn't work.
https://stackoverflow.com/questions/32745276/explicitly-set-disabled-false-in-the-html-does-not-work
It's better to remove the attribute all together

Remove 'disabled' instead of setting to false

---

src/app/ngx-mask/mask.directive.spec.ts
src/app/ngx-mask/mask.directive.ts

When `mask=""` ngx-mask not forward input value to form control at all. And when we call `this.form.value` it will be `undefined` and make the form completely useless.
I usually wrap an input in a component (eg `TextField` or `FormField` ) and control its state from there, then pass mask value down to the input. This sometimes make the input has an empty mask on non-masked fields and ngx-mask won't allow that.
Hope this help,
Porawit Poboonma

fix(directive): make it work even mask is empty

---

src/app/ngx-mask/mask.directive.ts

In IE 11 if I have multiple inputs with masks and I focus the first input and then focus the second, the two inputs keep focusing by themselves over and over again in an infinite loop causing the browser to hang:
You can see an example of the issue here is viewed in IE11:
https://stackblitz.com/edit/ngx-mask-issue?file=app/app.component.html
The issue is that setting the selectionStart & selectionEnd is triggering the input event to be fired again. I have added a check to only set the selection points if the element is the activeElement.

Fixing IE11 browser hang issue

---

src/app/ngx-mask/mask.service.ts

Fix a bug where an input is always rendered as disabled (disabled attribute is set) even when the control is enabled.

Fix disabled bug on input elements

---

README.md

Corrected markdown for two titles:
From:
###pipe with mask expression and custom Pattern ([string, pattern])
To:
And
From:
###repeat mask
To:

Add spaces for markdown

---

README.md
src/app/app.component.html
src/app/app.component.ts
src/app/ngx-mask/mask-applier.service.ts
src/app/ngx-mask/test/separator.spec.ts

Was trying to use these masks for currency and the main issue I had was inability to have nice thousands formatting AND limiting the number of decimals input (in my case 0 or 2)
Added additional overrides to the existing masks to allow setting a precision on the input.
Added tests for the base dot_separator and coma_separator as well as my precision versions.
Updated samples on main page and readme.
Hope this is okay; was needed for work project so just had to do something; let me know if you'd prefer any alterations or change to this.
I also didn't increment the package version; I couldn't tell if it was desired for contributers to make that change so I left it alone, but you might want to make sure you update the version number in the package-lock.json and the ng-package.json if it's …

Add precision checks to the dot_separator and comma_separator

---

.travis.yml

cache the node_modules folder for faster building and testing

feat: cache the node_modules folder

---

README.md

Readme.md file's example code has syntax error
escape character

readme example code error fix

---

README.md

Just a simple fix for the 24h mask example in the documentation.

24h format mask example now uses minute not month

---

src/app/ngx-mask/custom-keyboard-event.ts
src/app/ngx-mask/mask.directive.ts

in order to avoid server errors we have to patch the global object with
fake implementation of the KeyboardEvent and add a type alias so that
the global object patch is executed right before the event reference in the code
fixes https://github.com/JsDaddy/ngx-mask/issues/399

fix(mask-directive): replaced native KeyboardEvent with type alias

---

README.md
src/app/ngx-mask/config.ts
src/app/ngx-mask/ngx-mask.module.ts

added factory support for options in `NgxMaskModule.forRoot(options)` in order to
allow customPatterns support at root level with aot complition
fixes issue: #290

fix(ngx-mask-module): added options factory support

---

src/app/ngx-mask/mask.directive.ts

Avoids overwriting input element's value onFocus when value has not changed. This fixes an issue in some browsers where the cursor would jump to the end of the input text no matter where the cursor was inserted.

[Resolves #495] Mask Directive - Allow cursor insertion in mid. of input

---

README.md

`README.md` suffix example code has syntax error. So, I fixed it them. Thanks.

docs(readme): `sufix` to `suffix`

---

src/app/ngx-mask/mask.directive.ts
src/app/ngx-mask/test/basic-logic.spec.ts

Fix readonly input's model being emptied on backspace when all text is selected.
You can test the fix by modifying your demo app :
- In `app.component.html`, add `readonly` to any input.
- Example for the first date format input : `<input matInput placeholder="Date" readonly  mask="00/00/0000"  [(ngModel)]="formModelDate" 
[formControl]="formDate">`
- In `app.component.ts`, set a default value to the property matching the above input's `ngModel`
- Example for the date format input's model : `public formModelDate: SN = '12345678';`
- Launch the app
- Select all text in the modified input and press backspace.
- Result : 
- In the current version, the value will stay displayed in the input, but the ngModel and the FormControl values will be emptied.
- In the PR version, the value is still …

Fix readonly input's model being emptied

---

src/app/ngx-mask/mask.directive.ts

seems like setting the selection range to MAX_SAFE_INTEGER
on paste event breaks on Safari browser and places the caret
at the beginning of the input. This fix should calculate the
correct position of the input and place the caret accordingly
fixes issue #511

fix: fixed an issue where the caret jump at the beginning on Safari

---

src/app/ngx-mask/mask-applier.service.ts

An easy fix to resolve an issue with piping a number like 1.1 returns 11.

Allowed support for decimal values below 1000, eg. 1.1

---

projects/ngx-mask-lib/src/lib/mask-applier.service.ts
projects/ngx-mask-lib/src/test/separator.spec.ts

Based in issues from the community, it was made an enhancement in the main source code to add the feature which permits the end user to type negative values in fields configured with separator mask.
The main change was made in `_stripToDecimal` method as follows, which originally stripped all characters which were no digits. Now it keeps only one hyphen (minus signal) at the first character.
```javascript
private _stripToDecimal(str: string): string {
return str
.split('')
.filter((i: string, idx: number) => {
return i.match('^-?\\d') || i === '.' || i === ',' || (i === '-' && idx == 0)
})
.join('');
}
```
There were changes made to `separatorLimit` logic also, so that initial hyphen doesn't interfere on digit amount limiting.

Add feature to allow negative numbers in separator masked inputs

---

angular.json

Updates `angular.json` to correctly reference the relocated unit test files.

fix: update unit test configuration (#662)

---

README.md

Should solve some new user issues of copy pasting the example.
IE: This works mask="00/00/0000" but this will not work mask="{00/00/0000}"

Curly brace do not go around mask for inline mask

---

README.md
projects/ngx-mask-lib/src/lib/config.ts
projects/ngx-mask-lib/src/lib/mask-applier.service.ts
projects/ngx-mask-lib/src/lib/mask.directive.ts
projects/ngx-mask-lib/src/test/allow-negative-numbers.spec.ts
projects/ngx-mask-lib/src/test/utils/test-component.component.ts

Negative numbers are not correctly handled by the library, for instance if the input has the value `-123,456.45` the model would have the value of `123456.45` if  `dropSpecialCharacters` is set to `true`. If `dropSpecialCharacters` is set to `false` then the model would have the value of `-123,456.45` which then needs to be stripped of the comma for real world use so this change fixes that.
If you set `allowNegativeNumbers` to `true` and the input has the value of `-123,456.45`, then the model would have the correct value of `-123456.45`.

feat: #381 Allow negative numbers to be used and properly formatted

---

CHANGELOG.md
package-lock.json
package.json
projects/ngx-mask-lib/package.json
projects/ngx-mask-lib/src/lib/mask.directive.ts

Implement issue #738 
It might cause a breaking change if some use the directive on other elements than an `input` (ex: textarea like user in issue #493)

refactor(directive): change directive selector to input[mask]

---

README.md

Hi there!
I got an error saying that `const declarations must be initialized`. It should be simply repaired by initializing it to null. I updated the `README.md` page.

Options variable in app.module.ts is not initialized

---

projects/ngx-mask-lib/src/lib/mask-applier.service.ts

fix #635 
Removed hiddenInput and inputSymbol check. I'm not sure what it doing besides allowing '*'.

fix(mask-applier.service) The hiddenInput no longer allows asterisk

---

CHANGELOG.md
package.json
projects/ngx-mask-lib/package.json
projects/ngx-mask-lib/src/lib/mask.service.ts
projects/ngx-mask-lib/src/test/add-prefix.spec.ts

DropSpecialCharacters false also should return prefix 
Issue Number: #686

fix: dropSpecialCharacters false also should return prefix [ref:#686]

---

CHANGELOG.md
package.json
projects/ngx-mask-lib/package.json
projects/ngx-mask-lib/src/lib/mask-applier.service.ts
projects/ngx-mask-lib/src/test/test-sufix.spec.ts

Issue Number: #831 
Correctly remove suffix before applying mask, even if a part of it is deleted.

fix(mask-applier-service): remove complet mask if part of it is deleted

---

package-lock.json
projects/ngx-mask-lib/src/lib/mask.directive.ts
projects/ngx-mask-lib/src/test/dynamic.spec.ts

Issue Number: https://github.com/JsDaddy/ngx-mask/issues/763
The input value when set by the FormControl is masked accordingly with the dynamic mask

fix: #763 Dynamic mask initializes with wrong value

---

projects/ngx-mask-lib/src/lib/mask.service.ts
projects/ngx-mask-lib/src/test/secure-mask.spec.ts
src/app/bugs/bugs.component.html
src/app/bugs/bugs.component.ts

Issue Number: #863 #706 
It works

fix(hidden-input) input programmatically value set without phantom values

---

projects/ngx-mask-lib/src/lib/mask.directive.ts
projects/ngx-mask-lib/src/lib/mask.service.ts
projects/ngx-mask-lib/src/test/secure-mask.spec.ts

fix(#892): mask change doesn't change form pristine state

---

projects/ngx-mask-lib/src/lib/mask.directive.ts
projects/ngx-mask-lib/src/test/dynamic.spec.ts

When I try to change the mask from '(000)0000-000||(000)0000-0000||00-00000-00000' to '00-00-00-00'  directive does not clear `_maskExpressionArray` and if I update value in `FormControl` to remove extra characters directive will work with '(000)0000-000' mask instead of new '00-00-00-00'
After changing the mask, the directive will clear `_maskExpressionArray` if the new mask has only one string pattern.

fix(mask.directive.ts): _maskExpressionArray does not clear after change mask from several to one

---

CHANGELOG.md
package.json
projects/ngx-mask-lib/package.json
projects/ngx-mask-lib/src/lib/config.ts
projects/ngx-mask-lib/src/lib/mask-applier.service.ts
projects/ngx-mask-lib/src/lib/mask.directive.ts
projects/ngx-mask-lib/src/lib/mask.service.ts
projects/ngx-mask-lib/src/test/separator.spec.ts

Changed default configuration for decimalMarker ['.',','] instead '.'
Can use both decimal markers without additional configuration

fix(no-ref): separator logic

---

CHANGELOG.md
projects/ngx-mask-lib/src/lib/config.ts
projects/ngx-mask-lib/src/lib/mask.directive.ts
projects/ngx-mask-lib/src/lib/mask.service.ts
projects/ngx-mask-lib/src/test/delete.cy-spec.ts
projects/ngx-mask-lib/src/test/trigger-on-mask-change.cy-spec.ts
projects/ngx-mask-lib/src/test/trigger-on-mask-change.spec.ts
projects/ngx-mask-lib/src/test/utils/cypress-test-component.component.ts
projects/ngx-mask-lib/src/test/utils/cypress-test-trigger-on-mask-change.component.ts
projects/ngx-mask-lib/src/test/utils/cypress-test.module.ts
projects/ngx-mask-lib/src/test/utils/test-component.component.ts
src/app/showcase/showcase.component.html
src/app/showcase/showcase.component.ts

- Feature
If the mask is dynamically set via the mask input and the value changes, then the `onChange` is not called.
If we set `triggerOnMaskChange` and the value changes because the mask has e.g. a different length, then the `onChange` function is called with the new value.

feat(lib): allow mask change to trigger onChange

---

CHANGELOG.md
package-lock.json
package.json
projects/ngx-mask-lib/package.json
projects/ngx-mask-lib/src/lib/ngx-mask.directive.ts
projects/ngx-mask-lib/src/test/dynamic.spec.ts
src/assets/content/commonCases.ts

When an input with dynamic mask changes from the smaller mask to the bigger mask, the caret position (selectionStart) stays in the middle of the input, instead of going to the end of it
Issue Number: #1069 
When an input with dynamic mask changes from the smaller mask to the bigger mask, the caret position (selectionStart) goes to the end of it, following the typed text

fix(1069): input seleciontStart goes to wrong position after dynamic mask changes while typing

---

projects/ngx-mask-lib/src/lib/ngx-mask.directive.ts
projects/ngx-mask-lib/src/test/separator-non-en-locale.spec.ts

**EDIT: rebased on latest develop, added a test with FR locale (uses comma as decimal marker)**
to reproduce the issue:
- set decimalMarker .
- set browser locale to German for instance (so that decimal marker defaults to ',')
before fix: 1234.56 shows as 1234.5
after fix: 1234.56 shows as 1234.56
added unit test: `separator-non-en-locale.spec.ts`, which fails without the code change (you can simply let `NgxMaskDirective._currentLocaleDecimalMarker` return '.' and see it fail).
Issue Number: #1009
- set decimalMarker .
- set browser locale to German for instance (so that decimal marker defaults to ',')
before fix: 1234.56 shows as 1234.5
after fix: 1234.56 shows as 1234.56
fixes #1009

fix(1009): decimalMarker not locale default

---

projects/ngx-mask-lib/src/lib/ngx-mask.directive.ts
projects/ngx-mask-lib/src/test/default-config.spec.ts
projects/ngx-mask-lib/src/test/utils/test-component.component.ts

- [X ] The commit message follows our guidelines: https://github.com/JsDaddy/ngx-mask/blob/develop/CONTRIBUTING.md#commit
- [X ] Tests for the changes have been added (for bug fixes / features)
- [X ] Bugfix
Issue Number: 1066
If we set decimalMarker: "," in provideEnvironmentNgxMask(config) in app.module.ts, initial decimal number won't format correctly in input field (eg. 12.34 will appear as 1234). However, it will be formatted correctly if we explicitely define <input decimalMarker="," ...>.
Reproduction:
https://stackblitz.com/edit/angular-13-zhsicj?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.html
First input field relies on config options provided in module.app.ts and is not displayed correctly:
provideEnvironmentNgxMask({ …

fix(#1066): fixed decimal formatting bug when using provideEnvironmentNgxMask()

---

CHANGELOG.md
projects/ngx-mask-lib/package.json
projects/ngx-mask-lib/src/lib/ngx-mask.directive.ts
projects/ngx-mask-lib/src/lib/ngx-mask.service.ts
projects/ngx-mask-lib/src/test/emit-events.cy-spec.ts
projects/ngx-mask-lib/src/test/separator.spec.ts

Currently, no trailing zero is added when mask="separator.1" and leadZero="true" and input loses focus. This change adds the trailing zero in that case.
When `mask="separator.1"` and `leadZero="true"`, the input's value doesn't change when there is no decimal and the input loses focus. So, if `1` is entered in this case, the value remains `1` but the desired result is that the value would be changed to `1.0`.
Issue Number: #1358
When `1` is entered and the input loses focus, the value is replaced with `1.0`

fix(1358): add trailing zero when mask="separator.1" and leadZero="true"

---

CHANGELOG.md
package.json
projects/ngx-mask-lib/package.json
projects/ngx-mask-lib/src/lib/ngx-mask-applier.service.ts
projects/ngx-mask-lib/src/test/separator.cy-spec.ts

fix(ref: no-ref): fix issues

---

projects/ngx-mask-lib/src/lib/ngx-mask-applier.service.ts
projects/ngx-mask-lib/src/lib/ngx-mask.service.ts
projects/ngx-mask-lib/src/test/default-config.spec.ts
projects/ngx-mask-lib/src/test/provide-ngx-mask.spec.ts
projects/ngx-mask-lib/src/test/trigger-on-mask-change.spec.ts

Ensure that "triggerOnMaskChange" and "shownMaskExpression" are received in "NgxMaskService" when provided through "provideNgxMask()".
When values for "triggerOnMaskChange" and "shownMaskExpression" are provided through "provideNgxMask()", the configuration values don't flow through to the NgxMaskService and aren't applied to the <input> field.
Providing values for "triggerOnMaskChange" and "shownMaskExpression" through "provideNgxMask()" will inject the values into NgxMaskService which will be used when masking. For example:
```typescript
provideNgxMask({
triggerOnMaskChange: true,
showMaskTyped: true,
shownMaskExpression: '0000'
})
```

fix(config): Ensure that "triggerOnMaskChange" and "shownMaskExpression" are received in "NgxMaskService" when provided through "provideNgxMask()".

---

projects/ngx-mask-lib/src/lib/ngx-mask.directive.ts
projects/ngx-mask-lib/src/lib/ngx-mask.service.ts
projects/ngx-mask-lib/src/test/forms.spec.ts

Ensure that the masked value is propagated to the form control value when "inputTransformFn" is not an instance variable in the component.
If:
- a form control is modified via FormControl#setValue(),
- the value is transformed with a mask, and
- the component doesn't have an inputTransformFn.
Then, the underlying form control's value isn't updated with the new masked value.
Example in v19.0.6: https://stackblitz.com/edit/stackblitz-starters-chv17voi?file=src%2Fmain.ts
Example in v8.2.0: https://stackblitz.com/edit/stackblitz-starters-qfw8fjzy?file=src%2Fmain.ts
Ensures that the masked value is propagated to the form control value.
Ensure that the masked value is …

fix(forms): Propagate masked value to form control value.
