JsDaddy/ngx-mask

- src/app/ngx-mask/config.ts
- src/app/ngx-mask/mask.service.ts
- src/app/ngx-mask/ngx-mask.module.ts
This PR is fixing issues when it comes to config with AOT also the fact that the set initialization has to be in a function as well otherwise it will also break when AOT'ed
> aot config fixes

- package.json
- src/app/ngx-mask/mask.directive.ts
> It solves some problems with ngModel

- src/app/app.component.ts
- src/app/ngx-mask/mask.directive.spec.ts
- src/app/ngx-mask/mask.directive.ts
- src/app/ngx-mask/mask.service.ts
> add suport for pristine on init

- src/app/ngx-mask/mask.directive.ts
> Fix #115: allow setting null to formControl (inlcuding reactive reset)

- README.md
add brackets ([]) on "patterns" section in README.md
> added brackets ([]) on patterns

- src/app/ngx-mask/mask.service.ts
- src/app/ngx-mask/test/drop-special-charaters.spec.ts
Fix error applying mask when mask is coma_separator or dot_separator with decimal places different from 2.
Closes #309
> fix(service): Fix applyMask method (mask.service.ts)

- src/app/app.component.html
- src/app/app.component.ts
- src/app/ngx-mask/mask-applier.service.ts
- src/app/ngx-mask/mask.directive.ts
- src/app/ngx-mask/mask.service.ts
- src/app/ngx-mask/test/separator.spec.ts
Fixes issue #434 
@ValeriaKochegarova , @Thegrep01 , @NepipenkoIgor
> #434 - Fixed thousand separator

- src/app/ngx-mask/mask-applier.service.ts
when initializing MaskService, call MaskApplierService constructor but missing the config option "validation"
> module level option missing validation

- README.md
- package-lock.json
- src/app/app.component.html
- src/app/ngx-mask/config.ts
- src/app/ngx-mask/mask-applier.service.ts
- src/app/ngx-mask/mask.directive.ts
- src/app/ngx-mask/mask.service.ts
- src/app/ngx-mask/test/place-holder-character.spec.ts
- src/app/ngx-mask/test/utils/test-component.component.ts
> Allow placeholder customization

- CHANGELOG.md
- package-lock.json
- package.json
- projects/ngx-mask-lib/package.json
- projects/ngx-mask-lib/src/index.ts
> fix: issue #614 - export everything from config

- CHANGELOG.md
- package-lock.json
- package.json
- projects/ngx-mask-lib/package.json
- projects/ngx-mask-lib/src/lib/mask.directive.ts
- projects/ngx-mask-lib/src/lib/mask.service.ts
- projects/ngx-mask-lib/src/test/validation.spec.ts
- src/app/app.component.html
- src/app/app.component.ts
- src/app/app.module.ts
- tsconfig.json
Fix for #560 
Fix for #620 
Fix for #621
> fix: fix for #560 dynamic value for patterns attribute

- projects/ngx-mask-lib/src/lib/mask.directive.ts
Not sure do we really need this, but please check, should be useful.
Bug:
https://drive.google.com/file/d/1PMOdPK3ywjuQ5pMAWokel7lYD_hvcikg/view
Fix:
https://drive.google.com/file/d/1u4O7fpqaNTvlU1nbNncVOi5qNWMe4Tzs/view
> fix: limit selection to actual input length

- projects/ngx-mask-lib/src/lib/mask.directive.ts
Bug: 
https://drive.google.com/file/d/1sy8PnNJZezWUn2yumSGiLl5HwnmIbiCZ/view
Fixed version:
https://drive.google.com/file/d/1LuyB12BmO8GUgIthkukdT_bcb50YQYzb/view
> fix: put the cursor at the end if actual length reached

- CHANGELOG.md
- package-lock.json
- package.json
- projects/ngx-mask-lib/package.json
- projects/ngx-mask-lib/src/lib/mask.directive.ts
- projects/ngx-mask-lib/src/lib/mask.service.ts
- projects/ngx-mask-lib/src/lib/ngx-mask.module.ts
- src/app/bugs/bugs.component.html
- src/app/bugs/bugs.component.ts
- src/styles.scss
> fix: mark fields as touched even when mask is empty

- projects/ngx-mask-lib/karma.conf.js
- projects/ngx-mask-lib/src/lib/custom-keyboard-event.ts
- projects/ngx-mask-lib/src/lib/mask-applier.service.ts
- projects/ngx-mask-lib/src/lib/mask.directive.ts
- projects/ngx-mask-lib/src/test/percent.spec.ts
- projects/ngx-mask-lib/src/test/validation.spec.ts
- src/app/app.component.html
- src/karma.conf.js
- src/main.ts
> fix: allows percentage mask to limit precision

- projects/ngx-mask-lib/karma.conf.js
- projects/ngx-mask-lib/src/lib/custom-keyboard-event.ts
- projects/ngx-mask-lib/src/lib/mask-applier.service.ts
- projects/ngx-mask-lib/src/lib/mask.directive.ts
- projects/ngx-mask-lib/src/test/drop-special-charaters.spec.ts
- projects/ngx-mask-lib/src/test/validation.spec.ts
- src/app/app.component.html
- src/app/bugs/bugs.component.html
- src/app/bugs/bugs.component.ts
- src/app/showcase/showcase.component.html
- src/app/showcase/showcase.component.ts
- src/karma.conf.js
- src/main.ts
> fix: #743 Fixed erasing values with whitespace characters

- projects/ngx-mask-lib/src/lib/mask.directive.ts
- projects/ngx-mask-lib/src/lib/mask.service.ts
- projects/ngx-mask-lib/src/test/time-mask.spec.ts
take into account shifted simbol in time mask when showMaskTyped="true"
Closes #793
> fix(mask.service): apply time mask

- README.md
- projects/ngx-mask-lib/src/lib/config.ts
- projects/ngx-mask-lib/src/lib/mask-applier.service.ts
- projects/ngx-mask-lib/src/lib/mask.directive.ts
- projects/ngx-mask-lib/src/test/time-mask.spec.ts
- projects/ngx-mask-lib/src/test/utils/test-component.component.ts
add optional date/time mask with leading zeroes
Closes #779
> feat(mask-applier): add date/time leading zeroes

- .github/ISSUE_TEMPLATE/1-bug-report.md
- .github/ISSUE_TEMPLATE/2-feature-request.md
- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
- projects/ngx-mask-lib/src/lib/mask-applier.service.ts
- projects/ngx-mask-lib/src/lib/mask.directive.ts
- projects/ngx-mask-lib/src/lib/mask.service.ts
- projects/ngx-mask-lib/src/test/copy-paste.spec.ts
> fix: issue with copy paste event [ref:#765]

- CHANGELOG.md
- package-lock.json
- package.json
- projects/ngx-mask-lib/package.json
- projects/ngx-mask-lib/src/lib/mask.service.ts
- projects/ngx-mask-lib/src/test/basic-logic.spec.ts
- src/app/app.component.html
> fix(897): ghost characters shown in input when toggling mask on/off

- projects/ngx-mask-lib/src/lib/mask.directive.ts
Log input length
Issue Number: #988
Dont log input length
> chore: remove console log

- CHANGELOG.md
- package.json
- projects/ngx-mask-lib/package.json
- projects/ngx-mask-lib/src/lib/mask-applier.service.ts
- projects/ngx-mask-lib/src/test/copy-paste.spec.ts
> fix(#1000): cursor position after paste to input in mask with separator

- CHANGELOG.md
- package.json
- projects/ngx-mask-lib/package.json
- projects/ngx-mask-lib/src/lib/mask-applier.service.ts
- projects/ngx-mask-lib/src/test/basic-logic.spec.ts
> fix(#688): 'IP' mask validation

- CHANGELOG.md
- package.json
- projects/ngx-mask-lib/package.json
- projects/ngx-mask-lib/src/lib/mask.directive.ts
- projects/ngx-mask-lib/src/test/complete-mask.spec.ts
- projects/ngx-mask-lib/src/test/utils/cypress-test-component.component.ts
- projects/ngx-mask-lib/src/test/utils/cypress-test-shadow-dom.component.ts
- projects/ngx-mask-lib/src/test/utils/cypress-test-trigger-on-mask-change.component.ts
- projects/ngx-mask-lib/src/test/utils/test-component.component.ts
- projects/ngx-mask-lib/src/test/validation.spec.ts
- src/app/showcase/showcase.component.ts
> fix(#1017): replaced UntypedFormControl to FormControl

- .eslintignore
- README.md
- package.json
- projects/ngx-mask-lib/package.json
* feat(no-ref): change readme
* feat(no-ref): fix budge
Co-authored-by: Igor Nepipenko <inepipenko@muellerone.com>
> Fix/readme (#1057)

- src/assets/content/separators.ts
> fix: typo in separator.ts

- src/app/app.component.scss
- src/app/header/header.component.html
- src/app/header/header.component.scss
- src/app/header/header.component.ts
- src/app/options/options.component.scss
- src/app/shared/accordion/accordion.component.html
- src/app/shared/accordion/accordion.component.scss
- src/app/shared/accordion/accordion.component.ts
- src/app/sub-header/sub-header.component.scss
- src/assets/content/header.interface.ts
> feat(no-ref): fix styles where was important and few fix with OnInit

- src/app/header/header.component.scss
- src/app/options/options.component.html
- src/app/options/options.component.scss
- src/app/options/options.component.ts
- src/app/shared/accordion/accordion.component.html
- src/app/shared/accordion/accordion.component.scss
- src/app/shared/card-content/card-content.component.html
- src/app/shared/card-content/card-content.component.scss
- src/app/shared/card-content/card-content.component.ts
- src/styles.scss
> feat(no-ref): add reusable card-content

- .github/workflows/gh-pages.yml
> feat(no-ref): add command for gh-pages

- src/index.html
> fix(no-ref): change title

- package-lock.json
- src/app/app.component.ts
- src/app/options/options.component.html
- src/app/options/options.component.scss
> fix(no-ref): fix scroll cards

- src/app/app.component.html
- src/app/app.component.ts
- src/app/options/options.component.scss
> fix(no-ref): fix scroll navigation

- src/app/options/options.component.scss
> fix(no-ref): fix after qa

- src/app/options/options.component.scss
> fix(no-ref): fix frames

- CHANGELOG.md~
- projects/ngx-mask-lib/package.json
- projects/ngx-mask-lib/src/lib/ngx-mask.service.ts
> Fix(#1146)

- CHANGELOG.md
- projects/ngx-mask-lib/package.json
- projects/ngx-mask-lib/src/lib/ngx-mask-applier.service.ts
- projects/ngx-mask-lib/src/lib/ngx-mask.directive.ts
- projects/ngx-mask-lib/src/lib/ngx-mask.service.ts
- projects/ngx-mask-lib/src/test/add-prefix.spec.ts
- projects/ngx-mask-lib/src/test/delete.cy-spec.ts
- src/app/options/options.component.html
> fix(#889): fix 899

- CHANGELOG.md
- README.md
- projects/ngx-mask-lib/package.json
- projects/ngx-mask-lib/src/lib/ngx-mask-applier.service.ts
- projects/ngx-mask-lib/src/lib/ngx-mask.directive.ts
- projects/ngx-mask-lib/src/lib/ngx-mask.service.ts
- projects/ngx-mask-lib/src/test/dynamic.spec.ts
- src/assets/content/common-cases.ts
- src/assets/content/lists.ts
> Fix(#1071)

- CHANGELOG.md
- projects/ngx-mask-lib/package.json
- projects/ngx-mask-lib/src/lib/ngx-mask-applier.service.ts
- projects/ngx-mask-lib/src/lib/ngx-mask-expression.enum.ts
- projects/ngx-mask-lib/src/lib/ngx-mask.directive.ts
- projects/ngx-mask-lib/src/lib/ngx-mask.pipe.ts
- projects/ngx-mask-lib/src/lib/ngx-mask.service.ts
- projects/ngx-mask-lib/src/test/percent.spec.ts
- projects/ngx-mask-lib/src/test/repeat-mask.spec.ts
- projects/ngx-mask-lib/src/test/secure-mask.spec.ts
> fix(#1167): fix 1167

- CHANGELOG.md
- projects/ngx-mask-lib/package.json
- projects/ngx-mask-lib/src/lib/ngx-mask-applier.service.ts
- projects/ngx-mask-lib/src/lib/ngx-mask.directive.ts
- projects/ngx-mask-lib/src/lib/ngx-mask.service.ts
- projects/ngx-mask-lib/src/test/percent.spec.ts
- projects/ngx-mask-lib/src/test/separator-non-en-locale.spec.ts
- projects/ngx-mask-lib/src/test/utils/test-component.component.ts
- src/app/options/options.component.scss
> Fix(#1171)

- CHANGELOG.md
- projects/ngx-mask-lib/package.json
- projects/ngx-mask-lib/src/lib/ngx-mask-applier.service.ts
- projects/ngx-mask-lib/src/lib/ngx-mask-expression.enum.ts
- projects/ngx-mask-lib/src/lib/ngx-mask.directive.ts
- projects/ngx-mask-lib/src/lib/ngx-mask.service.ts
- projects/ngx-mask-lib/src/test/custom-date.spec.ts
- projects/ngx-mask-lib/src/test/separator.spec.ts
> Fix(#1166)

- CHANGELOG.md
- projects/ngx-mask-lib/src/lib/ngx-mask-applier.service.ts
- projects/ngx-mask-lib/src/lib/ngx-mask-expression.enum.ts
- projects/ngx-mask-lib/src/lib/ngx-mask.directive.ts
- projects/ngx-mask-lib/src/lib/ngx-mask.pipe.ts
- projects/ngx-mask-lib/src/lib/ngx-mask.service.ts
- projects/ngx-mask-lib/src/test/basic-logic.spec.ts
- projects/ngx-mask-lib/src/test/mask.pipe.spec.ts
> fix(#724): fix 724

- CHANGELOG.md
- projects/ngx-mask-lib/package.json
- projects/ngx-mask-lib/src/lib/ngx-mask-applier.service.ts
- projects/ngx-mask-lib/src/lib/ngx-mask.directive.ts
- projects/ngx-mask-lib/src/lib/ngx-mask.service.ts
- projects/ngx-mask-lib/src/test/secure-mask.spec.ts
- projects/ngx-mask-lib/src/test/separator.spec.ts
> fix(#1186): fix 1186

- CHANGELOG.md
- projects/ngx-mask-lib/package.json
- projects/ngx-mask-lib/src/lib/ngx-mask.directive.ts
- projects/ngx-mask-lib/src/lib/ngx-mask.service.ts~
- projects/ngx-mask-lib/src/test/drop-special-charaters.spec.ts
- projects/ngx-mask-lib/src/test/emit-events.cy-spec.ts
- projects/ngx-mask-lib/src/test/utils/cypress-test-component.component.ts
- src/app/options/options.component.html
> Fix(#1199)

- CHANGELOG.md
- package-lock.json
- package.json
- projects/ngx-mask-lib/package.json
- projects/ngx-mask-lib/src/lib/ngx-mask.directive.ts
- projects/ngx-mask-lib/src/test/validation.spec.ts
> fix(#1225): fix 1225

- CHANGELOG.md
- projects/ngx-mask-lib/package.json
- projects/ngx-mask-lib/src/lib/ngx-mask.service.ts
- projects/ngx-mask-lib/src/test/delete.cy-spec.ts
- projects/ngx-mask-lib/src/test/utils/cypress-test-component.component.ts
> fix(#1232): fix 1232

- CHANGELOG.md
- package-lock.json
- package.json
- projects/ngx-mask-lib/package.json
- projects/ngx-mask-lib/src/lib/ngx-mask.directive.ts
- projects/ngx-mask-lib/src/lib/ngx-mask.service.ts
- projects/ngx-mask-lib/src/test/basic-logic.spec.ts
- projects/ngx-mask-lib/src/test/show-mask-typed.spec.ts
> Fix(#1247)

- CHANGELOG.md
- package.json
- projects/ngx-mask-lib/package.json
- projects/ngx-mask-lib/src/lib/ngx-mask-applier.service.ts
- projects/ngx-mask-lib/src/lib/ngx-mask.directive.ts
- projects/ngx-mask-lib/src/test/cursor.cy-spec.ts
> fix(#1251): fix 1251

- .github/workflows/gh-pages.yml
> fix(#no-ref): 404 gh pages

- cypress.config.ts
> fix(ref: no-ref): restart release

- .github/.hooks/pre-commit/quality.sh
- .github/workflows/gh-pages.yml
- .github/workflows/quality-check.yml
- .github/workflows/scripts/quality
- .github/workflows/scripts/quality.sh
- .github/workflows/scripts/replace_template.sh
> fix(no-ref): add version for build v2

- .github/workflows/scripts/quality.sh
- .github/workflows/scripts/replace_template.sh
> fix(ref: no-ref): fix version

- .github/workflows/scripts/replace_template.sh
> fix(no-ref): add version for build v4

- .github/workflows/gh-pages.yml
> fix(no-ref): add version for build v5

- .github/workflows/gh-pages.yml
> fix(no-ref): add version for build v6

- CHANGELOG.md
- USAGE.md
- projects/ngx-mask-lib/package.json
- projects/ngx-mask-lib/src/lib/ngx-mask-applier.service.ts
- projects/ngx-mask-lib/src/lib/ngx-mask.directive.ts
- projects/ngx-mask-lib/src/lib/ngx-mask.pipe.ts
- projects/ngx-mask-lib/src/lib/ngx-mask.service.ts
- projects/ngx-mask-lib/src/test/add-prefix.spec.ts
- projects/ngx-mask-lib/src/test/delete.cy-spec.ts
- projects/ngx-mask-lib/src/test/drop-special-charaters.spec.ts
- projects/ngx-mask-lib/src/test/mask.pipe.spec.ts
- projects/ngx-mask-lib/src/test/percent.spec.ts
- projects/ngx-mask-lib/src/test/separator.spec.ts
- src/app/options/options.component.html
- src/app/options/options.component.ts
> feat(ref: #1295, #1292, #1314, #1310, #1304, #1308, #1299): fix issues

- .github/.hooks/commit-msg/check-commit-msg.sh
> feat(ref: no-ref): add commit msg to hooks

- CHANGELOG.md
- package.json
- projects/ngx-mask-lib/package.json
- projects/ngx-mask-lib/src/lib/ngx-mask-applier.service.ts
- projects/ngx-mask-lib/src/test/delete.spec.ts
* fix(ref: no-ref): fix issues
* fix(ref: no-ref): fix bugs
* fix(ref: no-ref): fix bugs
> fix(ref: no-ref): fix issues

- CHANGELOG.md
- package.json
- projects/ngx-mask-lib/package.json
- projects/ngx-mask-lib/src/lib/ngx-mask-applier.service.ts
- projects/ngx-mask-lib/src/test/basic-logic.spec.ts
- projects/ngx-mask-lib/src/test/cursor.cy-spec.ts
- projects/ngx-mask-lib/src/test/custom-patterns.spec.ts
- projects/ngx-mask-lib/src/test/delete.cy-spec.ts
* feat(ref: no-ref): fix issue
* feat(ref: no-ref): fix issue
* feat(ref: no-ref): fix issue
> feat(ref: no-ref): fix issue

- CHANGELOG.md
- package.json
- projects/ngx-mask-lib/package.json
- projects/ngx-mask-lib/src/lib/ngx-mask-applier.service.ts
- projects/ngx-mask-lib/src/test/delete.cy-spec.ts
> fix(ref: no-ref): fix issue

- .github/workflows/gh-pages.yml
- .github/workflows/publish.yml
- .github/workflows/quality-check.yml
-   [ ] The commit message follows our guidelines: https://github.com/JsDaddy/ngx-mask/blob/develop/CONTRIBUTING.md#commit
-   [ ] Tests for the changes have been added (for bug fixes / features)
-   [ ] Docs have been added / updated (for bug fixes / features)
-   [ ] Bugfix
-   [ ] Feature
-   [ ] Code style update (formatting, local variables)
-   [ ] Refactoring (no functional changes, no api changes)
-   [ ] Build related changes
-   [ ] CI related changes
-   [ ] Documentation content changes
-   [ ] Other... Please describe:
-   [ ] Yes
-   [ ] No
> fix(ref: no-ref): update workflows versions

- .github/workflows/publish.yml
- .github/workflows/quality-check.yml
- .github/workflows/scripts/quality.sh
-   [ ] The commit message follows our guidelines: https://github.com/JsDaddy/ngx-mask/blob/develop/CONTRIBUTING.md#commit
-   [ ] Tests for the changes have been added (for bug fixes / features)
-   [ ] Docs have been added / updated (for bug fixes / features)
-   [ ] Bugfix
-   [ ] Feature
-   [ ] Code style update (formatting, local variables)
-   [ ] Refactoring (no functional changes, no api changes)
-   [ ] Build related changes
-   [ ] CI related changes
-   [ ] Documentation content changes
-   [ ] Other... Please describe:
-   [ ] Yes
-   [ ] No
> fix(ref: 1440): add version lib version to slack

- README.md
> fix(ref:1534): logo size and readme content

- .github/scripts/replace_template.sh
- .github/workflows/gh-pages.yml
- .github/workflows/publish.yml
- .github/workflows/quality-check.yml
> fix(ref:no-ref): channel instead channel-id in workflow

- .github/workflows/gh-pages.yml
- .github/workflows/publish.yml
> fix(ref:no-ref):  channel in workflow
